<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
    Schema::create('cash_movements', function(Blueprint $t){$t->id();$t->uuid('transaction_uuid')->unique();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('cash_account_id')->constrained()->restrictOnDelete();$t->enum('movement_type',['deposit','withdrawal','transfer_in','transfer_out','adjustment'])->index();$t->decimal('amount',20,4);$t->dateTime('moved_at');$t->string('reference_type',100)->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->text('notes')->nullable();$t->timestamps();});
    Schema::create('cash_closings', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('cash_account_id')->constrained()->restrictOnDelete();$t->date('closing_date');$t->decimal('system_balance',20,4)->default(0);$t->decimal('counted_balance',20,4)->default(0);$t->decimal('variance',20,4)->default(0);$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->dateTime('closed_at')->nullable();$t->enum('status',['draft','closed','reopened'])->default('draft');$t->timestamps();$t->unique(['station_id','cash_account_id','closing_date']);});
    Schema::create('bank_transactions', function(Blueprint $t){$t->id();$t->uuid('transaction_uuid')->unique();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('cash_account_id')->constrained()->restrictOnDelete();$t->date('transaction_date');$t->string('bank_reference',100)->nullable();$t->string('description');$t->decimal('debit',20,4)->default(0);$t->decimal('credit',20,4)->default(0);$t->decimal('balance',20,4)->nullable();$t->enum('status',['unreconciled','reconciled','voided'])->default('unreconciled');$t->timestamps();});
    Schema::create('bank_reconciliations', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('cash_account_id')->constrained()->restrictOnDelete();$t->date('statement_date');$t->decimal('statement_balance',20,4)->default(0);$t->decimal('book_balance',20,4)->default(0);$t->decimal('difference',20,4)->default(0);$t->enum('status',['draft','in_progress','completed','cancelled'])->default('draft');$t->foreignId('prepared_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['station_id','cash_account_id','statement_date'],'bank_recon_station_account_date_unique');
});
    Schema::create('bank_reconciliation_items', function(Blueprint $t){$t->id();$t->foreignId('bank_reconciliation_id')->constrained()->cascadeOnDelete();$t->foreignId('bank_transaction_id')->constrained()->restrictOnDelete();$t->decimal('matched_amount',20,4);$t->text('notes')->nullable();$t->timestamps();$t->unique(['bank_reconciliation_id','bank_transaction_id']);});
    Schema::create('cost_centers', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->string('code',50);$t->string('name');$t->foreignId('parent_id')->nullable()->constrained('cost_centers')->nullOnDelete();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['station_id','code']);});
    Schema::create('accounting_rules', function(Blueprint $t){$t->id();$t->foreignId('station_id')->nullable()->constrained()->nullOnDelete();$t->string('transaction_type',80);$t->foreignId('debit_account_id')->constrained('chart_of_accounts')->restrictOnDelete();$t->foreignId('credit_account_id')->constrained('chart_of_accounts')->restrictOnDelete();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['station_id','transaction_type']);});
    Schema::create('customer_account_links', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('customer_id')->constrained()->restrictOnDelete();$t->foreignId('receivable_account_id')->constrained('chart_of_accounts')->restrictOnDelete();$t->foreignId('revenue_account_id')->nullable()->constrained('chart_of_accounts')->nullOnDelete();$t->timestamps();$t->unique('customer_id');});
    Schema::create('supplier_account_links', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('supplier_id')->constrained()->restrictOnDelete();$t->foreignId('payable_account_id')->constrained('chart_of_accounts')->restrictOnDelete();$t->foreignId('expense_account_id')->nullable()->constrained('chart_of_accounts')->nullOnDelete();$t->timestamps();$t->unique('supplier_id');});
    Schema::create('employee_account_links', function(Blueprint $t){$t->id();$t->foreignId('station_id')->constrained()->restrictOnDelete();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->foreignId('payable_account_id')->constrained('chart_of_accounts')->restrictOnDelete();$t->foreignId('salary_expense_account_id')->nullable()->constrained('chart_of_accounts')->nullOnDelete();$t->timestamps();$t->unique('employee_id');});
    Schema::table('journal_entry_lines', function(Blueprint $t){$t->foreignId('cost_center_id')->nullable()->after('account_id')->constrained()->nullOnDelete();$t->foreignId('customer_id')->nullable()->after('cost_center_id')->constrained()->nullOnDelete();$t->foreignId('supplier_id')->nullable()->after('customer_id')->constrained()->nullOnDelete();$t->foreignId('employee_id')->nullable()->after('supplier_id')->constrained()->nullOnDelete();$t->foreignId('generator_id')->nullable()->after('employee_id')->constrained()->nullOnDelete();$t->index(['cost_center_id','customer_id','supplier_id','employee_id','generator_id'],'journal_lines_dimensions_idx');});
 }
 public function down(): void {
    Schema::table('journal_entry_lines',function(Blueprint $t){$t->dropIndex('journal_lines_dimensions_idx');$t->dropForeign(['generator_id']);$t->dropForeign(['employee_id']);$t->dropForeign(['supplier_id']);$t->dropForeign(['customer_id']);$t->dropForeign(['cost_center_id']);$t->dropColumn(['generator_id','employee_id','supplier_id','customer_id','cost_center_id']);});
    foreach(['employee_account_links','supplier_account_links','customer_account_links','accounting_rules','cost_centers','bank_reconciliation_items','bank_reconciliations','bank_transactions','cash_closings','cash_movements'] as $table) Schema::dropIfExists($table);
 }
};
